name = "api"
compatibility_date = "2022-04-05"
route = { pattern = "dev-api.jonze.co", custom_domain = true }
vars = { ENVIRONMENT = "dev" }

[env.production]
route = { pattern = "api.jonze.co", custom_domain = true }
vars = { ENVIRONMENT = "production" }

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
